### ISSUE TITLE
Field to enter Username

### ISSUE THREAD

**Issue by Navya-K-N-24** [Luca-maxwell99/Code-Quest#10]
**User story**
 
As a beginner student, I want to add my username so that I can register my name on the Score board.
 
**Acceptance Criteria:**
 
- [ ] User can enter their username before starting the quiz.
 
**Tasks:**
 
- [ ] Create a username input field on the selection screen.

- [ ] Display the username during the quiz and on the results screen.
