### ISSUE TITLE
Responsive and accessible design

### ISSUE THREAD

**Issue by Navya-K-N-24** [Luca-maxwell99/Code-Quest#3]
**User story**
 
As a beginner student, I want to have a responsive design so that I can take the quiz on different devices like desktop, tablet, and mobile.

**Acceptance Criteria:**
- [ ] The quiz layout adjusts to different screen sizes
 
**Tasks:**
 
- [ ] Use CSS media queries to create a responsive design.

- [ ] Test the quiz on various devices and screen sizes.
