### ISSUE TITLE
Selecting the Quiz topic

### ISSUE THREAD

**Issue by Navya-K-N-24** [Luca-maxwell99/Code-Quest#4]
**User story**
 
As a beginner student, I want to select a quiz topic (HTML, CSS, or JavaScript) so that I can test my knowledge in a specific area.
 
**Acceptance Criteria:**
 
- [ ] User can choose between HTML, CSS, or JavaScript before starting the quiz.
 
**Tasks:**
 
- [ ] Create a dropdown with options for HTML, CSS, and JavaScript

- [ ] Implement a select and play functionality to start the quiz based on the selected topic.
